# Generated by Django 5.0.1 on 2026-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[("MALE", "Male Services"), ("FEMALE", "Female Services")],
                default="MALE",
                max_length=20,
            ),
        ),
    ]
