# Generated by Django 4.2.30 on 2026-08-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_service_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(default="Master Barber", max_length=100)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="Expert in precision cuts, fades, and traditional hot towel grooming.",
                    ),
                ),
                (
                    "avatar_icon",
                    models.CharField(
                        default="user-tie",
                        help_text="Font Awesome icon name (e.g. user-tie, user-ninja, user-doctor, crown)",
                        max_length=50,
                    ),
                ),
                (
                    "specialties",
                    models.CharField(
                        default="Skin Fade, Beard Styling, Hair Design", max_length=200
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
                ),
                ("experience_years", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Barber",
                "verbose_name_plural": "Barbers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.barber",
            ),
        ),
    ]
