# Generated by Django 4.2.30 on 2026-08-18

from django.db import migrations, models


def add_prashant_borhade(apps, schema_editor):
    Barber = apps.get_model('booking', 'Barber')
    Barber.objects.get_or_create(
        name='Prashant Borhade',
        defaults={
            'title': 'Master Barber',
            'bio': 'Specialist in precision fades, beard styling, and classic grooming.',
            'avatar_icon': 'user-tie',
            'specialties': 'Skin Fades, Beard Styling, Classic Cuts',
            'rating': 4.9,
            'experience_years': 7,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_barber_booking_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
        migrations.RunPython(add_prashant_borhade, migrations.RunPython.noop),
    ]
