# Generated by Django 4.2.30 on 2026-08-18 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0005_barber_photo_and_prashant"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional shop account that signs this barber into their personal dashboard.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barber_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
