# Generated by Django 4.2.30 on 2026-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_barber_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Shop Setting",
                "verbose_name_plural": "Shop Settings",
            },
        ),
    ]
