# Generated by Django 5.1.6 on 2026-08-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_shopsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
