# Generated by Django 5.1.6 on 2026-08-23 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_payment_razorpay_order_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_signature",
        ),
        migrations.AddField(
            model_name="payment",
            name="is_verified_by_barber",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="UPI", max_length=50),
        ),
    ]
