# Generated by Django 5.1.6 on 2026-08-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_remove_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="All selected services",
                related_name="multi_bookings",
                to="booking.service",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                help_text="Primary service",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.service",
            ),
        ),
    ]
